[package]
name = "esp"
version = "1.0.0"
edition = "2024"

[dependencies]
simd-adler32 = { version = "*", default-features = false }
bytebuffer = "*"
crc32fast = "*"

[dev-dependencies]
globed-derive = { path = "../derive" }
