[package]
name = "globed-game-server"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globed-shared = { path = "../shared" }
globed-derive = { path = "../derive" }
esp = { path = "../esp" }

alloca = "0.4.0"
ctrlc = "3.4.4"
rustc-hash = "1.1.0"
serde = { version = "1.0.202", features = ["serde_derive"] }
serde_json = "1.0.117"
futures-util = "0.3.30"
console-subscriber = { version = "0.2.0", features = ["parking_lot"] }

tokio_tracing = { package = "tokio", version = "1.37.0", features = [
    "full",
    "tracing",
], optional = true }
tokio = { version = "1.37.0", features = ["full"], optional = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "globed-bench"
path = "benchmarks/bench.rs"
harness = false

[[test]]
name = "globed-tests"
path = "tests/test.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }

[features]
default = ["tokio"]
use_tokio_tracing = ["tokio_tracing"]
