#pragma once
#include <Geode/Result.hpp>
#include <Geode/loader/Log.hpp>
#include <algorithm>
#include <array>
#include <atomic>
#include <core/net/data/generated.hpp>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <fmt/format.h>
#include <functional>
#include <iterator>
#include <limits>
#include <memory>
#include <optional>
#include <span>
#include <std23/move_only_function.h>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>